### ISSUE TITLE
Learn how to expose webservices, i.e. Jupyter Notebook

### ISSUE THREAD

**Issue by ofrei** [comorment/gwas#6]
I'm fairly sure both singularity and docker can expose a webservice, i.e. something like Jupyter Notebook that is running within container, but you access it from your host via browser. Can we have include instructions on how to use this, for example with Jupyter Notebook?

**Comment by bayramakdeniz** [comment]
For docker, this can be done such as:

docker run -p 8888:8888 -v ~/notebooks2:/AA  trial5 jupyter notebook --ip=0.0.0.0 --allow-root

For singularity, I am looking for a solution

**Comment by ofrei** [comment]
@bayramakdeniz Let me know if I can help with this in any way - I'm also happy to help looking for a solution.

**Comment by ofrei** [comment]
Does any of this help?
https://vsoch.github.io/lessons/sherlock-singularity/
https://neurostars.org/t/jupyter-notebook-in-singularity-image/2431
https://stackoverflow.com/questions/54592769/how-to-run-a-jupyter-notebook-using-a-singularity-image

**Comment by bayramakdeniz** [comment]
Many thanks, it seems it works in this manner:

singularity exec --bind your/path/:/AA --bind $PWD:/run/user  gwastools.sif jupyter notebook --notebook-dir=/AA   --no-browser --ip=127.0.0.1

**Comment by ofrei** [comment]
Could you double-check if there is a way to map ports in singularity - something similar to docker's ``-p 8888:8888``?

**Comment by bayramakdeniz** [comment]
Yes we can, but there is a difference. In docker we need to expose some port  (say 8080) to Docker to run Jupyter Notebook. This can be done as 

`` docker run -p 8080:8080 -v ~/notebooks2:/AA gwastools  jupyter notebook --ip=0.0.0.0 --allow-root --port=8080 ``

Then we can have link and run jupyter notebook via a link something like: http://0.0.0.0:8080/?token=5f6e3422e3681de8cdd07a56a8a95d72bd4bb8ac076cace1

Naturally if we choose 8888 instead of  8080 as  Jupyter port:  `` docker run -p 8080:8080 -v ~/notebooks2:/AA gwastools  jupyter notebook --ip=0.0.0.0 --allow-rt --port=8888 `` and try to run the corresponding link

`` http://0.0.0.0:8888/?token=4d026719cd7fb031fc2dd364bd329320f67020df23413fc5 ``

we will fail since 8888 is not dedicated to corresponding container.


For the singularity on the other hand, this is not required (due to difference in network isolation: https://stackoverflow.com/questions/47297645/binding-ports-when-running-docker-images-in-singularity), But we still of course run Jupyter Notebook with a dedicated port as:
`` 
singularity exec --bind magicsquare:/AA --bind $PWD:/run/user gwastools.sif jupyter notebook --notebook-dir=/AA --no-browser --ip=0.0.0.0 --port=8888 
`` 
and launch the corresponding link easily. We can assign any port instead of --port=8888.  On the other hand, for the docker if we run without -p 8888:8888, we  can not launch the corresponding link since it is not dedicated to corresponding docker container.

**Comment by ofrei** [comment]
I will test this - it's quite important to have Jupyter working via singularity.

**Comment by f-krull** [comment]
Maybe relevant: A long time ago I built a singularity container for Osman to run jupyter inside TSD

https://github.com/precimed/tsdtools/tree/da6c327af502a7de35245dcc700ff2037a30b704/src/contsoft (note: do not use HEAD)

In earlier versions of singularity it wasn't necessary to expose ports - they are already exposed by default. The application is opening the port directly on the host

**Comment by ofrei** [comment]
@f-krull cool, thanks!
Another part of this repo sets up VS Code - this is really interesting. We discussed with @bayramakdeniz  if it's possible to expose GUI from within singularity container. Bayram made a demo with Octave GUI - it worked on his machine, but not TSD. My guess was that this is  because the container and the host had Ubuntu, but moving Ubuntu-based GUI into CentOS-based TSD machines failed. Now I see your container has Ubuntu 16.04, yet it has VS Code.

**Comment by f-krull** [comment]
@ofrei The repo is a bit messy and I would do things differently today. But with this code I was able to set up a jupyter that was working for Osman. So it might still be a starting point.
I didn't end up using the vs code - At that time I hadn't found a good way how to map all relevant TSD directories with singularity.

**Comment by ofrei** [comment]
@bayramakdeniz jupyter works like a charm with our python3.sif container. The command  can be even simpler, e.g. like this:
```
singularity exec --contain --home $PWD:/home python3.sif jupyter notebook  --no-browser --port 8890
```
I.e. after switching to ``--home`` it was ok to omit ``--notebook-dir``. 
The ``ip=127.0.01`` was redundant. But it was good to specify the ``--port``, because if one runs jupyter on a remote machine, it's important to map ports (as described here https://wiki.norment.uiocloud.no/dokuwiki/tsd_software).
